apiVersion: v1
kind: Secret
metadata:
  name: lmferbel-secret-tls
type: kubernetes.io/tls
data:
  tls.crt: .crt file content( but u have to convert it to base64 as security practice)  $base64 -w 0 file.txt
  tls.key: .key file content( but u have to convert it to base64 as security practice)
  
To generate certificate using certbot first we should install certboy using this command
sudo apt install certbot
Then generate the certificate and the private key using the following command
this command is usefull for subdomains
certbot certonly --manual \
  --preferred-challenges=dns \
  --email marcin@hotmail.com \
  --server https://acme-v02.api.letsencrypt.org/directory \
  --agree-tos \
  --manual-public-ip-logging-ok \
  -d “*.lmferbel.me”
for a main domain use the following commands:
$apt install certbot python3-certbot-nginx
$certbot --nginx -d lmferbel.me
$kubectl get secret --namespace cattle-system bootstrap-secret -o go-template='{{.data.bootstrapPassword|base64decode}}{{"\n"}}' in case off rancher deployement
$kubectl create -n cattle-system secret tls my-tls-secret --key privkey.pem --cert cert.pem # if you want to create ssl certificate using private key and certificate
use this command
