apiVersion: v1
kind: secret
metadata:
  name: myapp-secret-tls
type: kubernetes.io/tls
data:
  tls.crt: .crt file content( but u have to convert it to base64 as security practice)
  tls.key: .key file content( but u have to convert it to base64 as security practice)
