apiVersion: k8s.networking.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec: 
  tls:
  - hosts:
    - lmferbel.me
    secretName: myapp-secret-tls
  rules:
    host:
    - name: lmferbel.me
      http:
        paths:
        - path: "/"
          pathType: Prefix
          backend:
            service: 
              name: myapp-internal-service
              port: 
                number: 80





