apiVersion: v1
kind: secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  username: a choosen username( but u have to convert it to base64 as security practice)
  password: a choosen password( but u have to convert it to base64 as security practice)
