appName: checkoutservice
appImage: gcr.io/google-samples/microservices-demo/checkoutservice
apptag: v.0.2.3
replicaCount: 2
containerPort: 5050
containerEnvPort:
- name: PORT
  value: "5050"
- name: PRODUCT_CATALOG_SERVICE_ADDR
  value: "productcatalogservice:3550"
- name: SHIPPING_SERVICE_ADDR
  value: "shippingservice:50051"
- name: PAYMENT_SERVICE_ADDR
  value: "paymentservice:50051"
- name: EMAIL_SERVICE_ADDR
  value: "emailservice:5000"
- name: CART_SERVICE_ADDR
  value: "cartservice:7070"

serviceType: ClusterIP
servicePort: 5050