apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-reader-rb
roleRef:
  name: audit-reader
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: audit-sa
  kind: ServiceAccount
  namespace: default